version: "3.9"
services:
  db:
    image: mysql
    volumes:
      - data_db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    container_name: tm-db
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: .
    container_name: tm-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
  app_frontend:
    container_name: tm-app-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/frontend/
      - node_modules:/frontend/node_modules/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  data_db:
  node_modules: